/* tslint:disable */
/* eslint-disable */
/**
 * Payment API
 * Payment service for movie tickets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface PaymentDTO
 */
export interface PaymentDTO {
    /**
     * Total Price
     * @type {number}
     * @memberof PaymentDTO
     */
    totalPrice: number;
    /**
     * Transaction Id
     * @type {string}
     * @memberof PaymentDTO
     */
    transactionId: string;
}

/**
 * PaymentApi - axios parameter creator
 * @export
 */
export const PaymentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PaymentDTO} paymentDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerPayForBooking: async (paymentDTO: PaymentDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentDTO' is not null or undefined
            assertParamExists('paymentControllerPayForBooking', 'paymentDTO', paymentDTO)
            const localVarPath = `/booking`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication backendToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paymentDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentApi - functional programming interface
 * @export
 */
export const PaymentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PaymentDTO} paymentDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerPayForBooking(paymentDTO: PaymentDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerPayForBooking(paymentDTO, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PaymentApi - factory interface
 * @export
 */
export const PaymentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentApiFp(configuration)
    return {
        /**
         * 
         * @param {PaymentDTO} paymentDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerPayForBooking(paymentDTO: PaymentDTO, options?: any): AxiosPromise<void> {
            return localVarFp.paymentControllerPayForBooking(paymentDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentApi - object-oriented interface
 * @export
 * @class PaymentApi
 * @extends {BaseAPI}
 */
export class PaymentApi extends BaseAPI {
    /**
     * 
     * @param {PaymentDTO} paymentDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerPayForBooking(paymentDTO: PaymentDTO, options?: any) {
        return PaymentApiFp(this.configuration).paymentControllerPayForBooking(paymentDTO, options).then((request) => request(this.axios, this.basePath));
    }
}


